### ISSUE TITLE
Update schema location of DeleteObservation operation?!

### ISSUE THREAD

**Issue by autermann** [52North/arctic-sea#3]
Shouldn't we point to another source for the schema of the delete observation operation because it will be removed someday?

The link used in the [source code](https://github.com/52North/shetland/blob/master/src/main/java/org/n52/shetland/ogc/sos/delobs/DeleteObservationConstants.java#L56):
```java
    String NS_SOSDO_1_0_SCHEMA_LOCATION =
            "https://raw.githubusercontent.com/52North/SOS/master/extensions/do/xml/src/main/xsd/sosdo.xsd";
```

What about using `http://52north.org/schema/sosdo/1.0|2.0/sosdo.xsd`?
  

See https://github.com/52North/shetland/issues/1.

**Comment by autermann** [comment]
Definitely not this issue....

**Comment by ridoo** [comment]
Pointing to https://52north.org/schema/ makes definitely sense IMHO

**Comment by CarstenHollmann** [comment]
Already fixed in commit https://github.com/52North/shetland/commit/c2bf058bbe83e21434ed92a1828c30927f3e1890

**Comment by EHJ-52n** [comment]
autermann wrote
> How about https://schema.52north.org? We could create a repository on GitHub to collect schemas and serve them over that domain. Either by using [GitHub pages](https://help.github.com/articles/setting-up-a-custom-subdomain/) or by hosting it ourselves.

I like this approach, especially the github pages part. Is anyone of you able to start something or should we do this during the 52n-days?

**Comment by autermann** [comment]
The problem is that GitHub Pages does not support SSL for custom domains...

But we could host it ourselves and use our Jenkins instance to deploy a GitHub repository.

**Comment by autermann** [comment]
I've created https://github.com/52North/schema with the current content of https://52north.org/schema as first step...
